# **DATA FRAME: Đọc - ghi file**

**1. Đọc ghi file trực tiếp**

In [2]:
import pandas as pd

In [4]:
# Khởi tạo dữ liệu dạng dictionary
data = {
    'name': ['Minh Anh', 'Lâm Khánh', 'Tuấn Linh', 'Duy Anh', 'Thu Hương'],
    'age': [15, 15, 16, 17, 17],
    'gender': ['male', 'male', 'male', 'male', 'female']
}
# Khởi tạo DataFrame
df = pd.DataFrame(data)
# Hiển thị dữ liệu từ dataframe
df

        name  age  gender
0   Minh Anh   15    male
1  Lâm Khánh   15    male
2  Tuấn Linh   16    male
3    Duy Anh   17    male
4  Thu Hương   17  female

**Tạo và đọc dữ liệu**

In [7]:
# Tạo dữ liệu CSV
df.to_csv('data.csv', index=False)

# Đọc dữ liệu
df_csv = pd.read_csv('data.csv')
df_csv

        name  age  gender
0   Minh Anh   15    male
1  Lâm Khánh   15    male
2  Tuấn Linh   16    male
3    Duy Anh   17    male
4  Thu Hương   17  female

In [8]:
# Tải file về máy
from google.colab import files
files.download('data.csv')

In [9]:
# Tạo dữ liệu xlsx
df = pd.DataFrame(data)
df.to_excel('output.xlsx', index=False)
# Đọc dữ liệu từ file xlsx
df_read = pd.read_excel('output.xlsx', sheet_name='Sheet1')
print(df_read)

        name  age  gender
0   Minh Anh   15    male
1  Lâm Khánh   15    male
2  Tuấn Linh   16    male
3    Duy Anh   17    male
4  Thu Hương   17  female

In [10]:
# Tạo dữ liệu json
df = pd.DataFrame(data)
df.to_json('output.json', orient='records')
# Đọc dữ liệu từ file json
df_read = pd.read_json('output.json')
print(df_read)

        name  age  gender
0   Minh Anh   15    male
1  Lâm Khánh   15    male
2  Tuấn Linh   16    male
3    Duy Anh   17    male
4  Thu Hương   17  female

**2. Đọc dữ liệu từ file có sẵn (trong máy tính)**

In [11]:
# Tải file lên
from google.colab import files
files.upload()

Saving zoo.csv to zoo.csv

{'zoo.csv': b'row_number,animal,sound\n1,dog,woof\n2,cat,meow\n3,bird,tweet\n4,mouse,squeek\n5,cow,moo\n6,cow,moo\n7,frog,croak\n8,bird,tweet\n9,elephant,toot\n10,duck,quack\n11,fish,blub\n12,frog,croak\n13,seal,ow ow ow\n14,fox,'}

In [12]:
# Đọc file zoo.csv
  # index_col = 0: sử dụng cột đầu tiên trong dữ liệu để làm index
df = pd.read_csv('zoo.csv', index_col=0)
df

              animal     sound
row_number
1                dog      woof
2                cat      meow
3               bird     tweet
4              mouse    squeek
5                cow       moo
6                cow       moo
7               frog     croak
8               bird     tweet
9           elephant      toot
10              duck     quack
11              fish      blub
12              frog     croak
13              seal  ow ow ow
14               fox       NaN

In [13]:
# rename_axis(): đổi tên trục - axis (ngang hoặc dọc)
  # index (axis = 0): trục hàng
  # columns (axis = 1): trục cột

df = df.rename_axis(index=None) # xóa tên cột index
df

      animal     sound
1        dog      woof
2        cat      meow
3       bird     tweet
4      mouse    squeek
5        cow       moo
6        cow       moo
7       frog     croak
8       bird     tweet
9   elephant      toot
10      duck     quack
11      fish      blub
12      frog     croak
13      seal  ow ow ow
14       fox       NaN

# **TRUY CẬP DỮ LIỆU**

**1. Truy cập theo cột: DataFrame[column]**

In [15]:
# Truy cập cột 'animal' của df
animals = df['animal']
animals.head(3)

1     dog
2     cat
3    bird
Name: animal, dtype: object

In [17]:
# Hiển thị 3 bản ghi cuối của cột 'sound'
sounds = df['sound']
sounds.tail(3)

12       croak
13    ow ow ow
14         NaN
Name: sound, dtype: object

Lưu ý: NaN là viết tắt của Not a Number. <br>
Trong pandas, NaN dùng để biểu diễn dữ liệu bị thiếu (missing data)

In [19]:
# Truy cập nhiều cột: DataFrame[[col1, col2, ...]]
multi_col = df[['animal', 'sound']].tail(3)
multi_col

   animal     sound
12   frog     croak
13   seal  ow ow ow
14    fox       NaN

**2. Truy cập theo hàng**

slice[start:end] => chạy từ start đến end-1

In [20]:
# Hiện từ hàng 5 đến 8
animals[4:8]

5     cow
6     cow
7    frog
8    bird
Name: animal, dtype: object

In [21]:
# Hiện 4 hàng đầu tiên
animals[:4]

1      dog
2      cat
3     bird
4    mouse
Name: animal, dtype: object

In [23]:
# Hiện từ dòng số 10 đến hết
animals[9:]

10    duck
11    fish
12    frog
13    seal
14     fox
Name: animal, dtype: object

**3. Truy cập theo cả hàng và cột**

DataFrame.iloc[rows, columns]

In [28]:
# Hiển thị 3 dòng đầu tiên của cột thứ 2
df.iloc[:3, 1:2]

   sound
1   woof
2   meow
3  tweet

**4. Truy cập có điều kiện**

In [29]:
# Tìm bản ghi mà data cột 'animal' == 'cat'
target = df[df['animal'] == 'cat']
target

  animal sound
2    cat  meow

# **Tổng hợp 1 số lệnh hay dùng với DataFrame**

In [30]:
# Khởi tạo dữ liệu dạng dictionary
data = {
    'name': ['Minh Anh', 'Lâm Khánh', 'Tuấn Linh', 'Duy Anh', 'Thu Hương'],
    'age': [15, 15, 16, 17, 17],
    'gender': ['male', 'male', 'male', 'male', 'female']
}
# Khởi tạo DataFrame
df = pd.DataFrame(data)
# Hiển thị dữ liệu từ dataframe
df

        name  age  gender
0   Minh Anh   15    male
1  Lâm Khánh   15    male
2  Tuấn Linh   16    male
3    Duy Anh   17    male
4  Thu Hương   17  female

In [31]:
# Xem kiểu dữ liệu của từng cột
df.dtypes

name      object
age        int64
gender    object
dtype: object

In [32]:
# Xem số hàng và cột
df.shape

(5, 3)

In [33]:
# Tóm tắt thông tin của DataFrame: số dòng, số cột, số giá trị có dữ liệu, kiểu dữ liệu
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   gender  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [34]:
# Thống kê các cột dạng số
    # count: số dữ liệu (bản ghi)
    # mean: trung bình
    # std: độ lệch chuẩn
    # min, max: giá trị lớn/nhỏ nhất
df.describe()

        age
count   5.0
mean   16.0
std     1.0
min    15.0
25%    15.0
50%    16.0
75%    17.0
max    17.0

In [36]:
# Hiển thị các dòng đầu: df.head(n)
df.head(2)

        name  age gender
0   Minh Anh   15   male
1  Lâm Khánh   15   male

In [37]:
# Hiển thị các dòng cuối: df.tail(n)
df.tail(3)

        name  age  gender
2  Tuấn Linh   16    male
3    Duy Anh   17    male
4  Thu Hương   17  female

In [40]:
# Đổi tên trục: rename_axis()
    # index (axis=0) → trục hàng
    # columns (axis=1) → trục cột
df = df.rename_axis(index=None) # Xóa tên cột index
df

        name  age  gender
0   Minh Anh   15    male
1  Lâm Khánh   15    male
2  Tuấn Linh   16    male
3    Duy Anh   17    male
4  Thu Hương   17  female

In [44]:
# Đặt 1 cột làm index: set_index()
df = df.set_index('name')
df

           age  gender
name
Minh Anh    15    male
Lâm Khánh   15    male
Tuấn Linh   16    male
Duy Anh     17    male
Thu Hương   17  female

In [45]:
# Đưa index trở lại thành cột: reset_index()
df.reset_index()

        name  age  gender
0   Minh Anh   15    male
1  Lâm Khánh   15    male
2  Tuấn Linh   16    male
3    Duy Anh   17    male
4  Thu Hương   17  female

In [47]:
# Đổi tên cột hoặc index: df.rename(columns={"old_name":"new_name"})
df = df.rename(columns={"age":"tuổi"})
df

           tuổi  gender
name
Minh Anh     15    male
Lâm Khánh    15    male
Tuấn Linh    16    male
Duy Anh      17    male
Thu Hương    17  female